--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fernanACM/AntiSpamPro
build-by-default: true
branches:
- main
projects:
  AntiSpamPro:
    path: ""
    icon: icon.png
    lint:
      phpstan: false
...
