#     _            _     _   ___                         ___             
#    /_\    _ _   | |_  (_) / __|  _ __   __ _   _ __   | _ \  _ _   ___ 
#   / _ \  | ' \  |  _| | | \__ \ | '_ \ / _` | | '  \  |  _/ | '_| / _ \
#  /_/ \_\ |_||_|  \__| |_| |___/ | .__/ \__,_| |_|_|_| |_|   |_|   \___/
#       By fernanACM and awzaw    |_|                                    
            
#The delay is the minimum time in seconds allowed between chats, including warnings.
#message to be sent if the player is sending spam
#action to take after warnings, "kick" or "ban"
#Kick message is displayed when kicking
#warnings is the number of violations before action is taken

# Prefix
Prefix: "§l§7[§cAntiSpamPro§7]§8»§r "

# Chat Cooldown
Cooldown: 2
Set-Cooldown: "AntiSpamPro settings have been changed"
Invalid-Cooldown: "Please use a valid delay (1, 2 or 3)"

# Cooldown Messages
Message1: "Please be polite, do not chat too fast"
Message2: "For help and chat join DISCORD at §6https://discord.gg/YyE9XFckqb"

# Chat sanctions
Action: "kick" # kick or ban
kick-Message: "§cDon't spam, next time it will be a more drastic penalty"
SetKickMessage: "Spammers will be kicked"
SetBanMessage: "Spammers will be banned"
SetBanipMessage: "Spammers will be IP banned"
SetBancidMessage: "Spammers will be CID banned"
Ban-Message: "No Spam"

# Warnings Messages
warnings: 5
Last-Warning: "CAREFUL... LAST WARNING"

# Help Message
help: "/asp help"
help2: "/asp set 2 (set minimum delay (1,2 or 3)"
# Rude filter
Swear-Message: "No Swear Words Allowed"
AntiSwearWords: true
AntiRudeNames: true
